apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:readonly

  policy.csv: |
    # Rôle dev-guestbook
    p, role:dev-guestbook, applications, get, guestbook-project/guestbook, allow
    p, role:dev-guestbook, applications, sync, guestbook-project/guestbook, allow
    p, role:dev-guestbook, applications, action/*, guestbook-project/guestbook, allow

    # Mapper un utilisateur local (exemple)
    g, guestbook-dev, role:dev-guestbook
