apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-dev
  namespace: argocd
spec:
  project: guestbook-project
  source:
    repoURL: git@github.com:kaninda/guestbook-app-kustomize.git
    targetRevision: master
    path: overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook-kustomize-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
