apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: guestbook-project
  namespace: argocd
spec:
  description: Project for guestbook application
  # Repos Git autorisés
  sourceRepos:
    - git@github.com:kaninda/argocd-example-apps.git
  # Destinations autorisées
  destinations:
    - namespace: guestbook
      server: https://kubernetes.default.svc
  # Ressources autorisées (optionnel mais propre)
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: apps
      kind: Deployment
    - group: ""
      kind: Service