apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-helm-dev
  namespace: argocd
spec:
  project: guestbook-project
  source:
    repoURL: git@github.com:kaninda/guestbook-app-helm.git
    targetRevision: master
    path: .
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook-helm-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true